import type {
  AccountState, AgentGrant, GasRow, NovationClient, ProtocolStats, Quote, Refusal, ScenarioGrid, Series, Session, Underlying, Vault,
  Venue, WhatIfOptions,
} from './types';
import underlyingsJson from '../../fixtures/underlyings.json';
import chainsJson from '../../fixtures/chains.json';
import account7Json from '../../fixtures/account7.json';
import whatifsJson from '../../fixtures/whatifs.json';
import marketMakerJson from '../../fixtures/market-maker.json';
import vaultsJson from '../../fixtures/vaults.json';
import agentsJson from '../../fixtures/agents.json';
import protocolJson from '../../fixtures/protocol.json';
import refusalsJson from '../../fixtures/refusals.json';
import gasJson from '../../fixtures/gas.json';
import { buildBook, defaultParams, kernelMargin, RISK, withTrade } from '../kernel';

type ChainSeries = Series & { bid: number; ask: number; delta: number; iv: number };
type AccountData = Awaited<ReturnType<NovationClient['account']>>;

/** tools/ref/gen_app_fixtures.py NOW: every fixture mark, grid and margin is priced at this second. */
export const FIXTURE_AS_OF = 1790697600;
const FEE_BPS = 5;
/** How far a premium may sit from the canned ticket's and still be that ticket (USDG). */
const PREMIUM_TOLERANCE = 0.01;
type CannedTicket = {
  id: number;
  seriesId: number;
  qtyDelta: number;
  premium: number;
  venue?: Venue;
  agent?: string;
  quote: Quote;
};
const MM_RATIO = RISK.mmRatio;
const account7 = account7Json as unknown as {
  account: AccountData;
  grids: Record<string, { cells: number[]; shockRange: Record<string, number> }>;
};
const marketMaker = marketMakerJson as unknown as AccountData & { grid: number[] };
const clone = <T,>(v: T): T => structuredClone(v);
const chains = chainsJson as unknown as Record<string, { expiries: number[]; series: ChainSeries[] }>;
const seriesById = new Map<number, ChainSeries>(Object.values(chains).flatMap((c) => c.series.map((s) => [s.id, s] as const)));

/** Reads the fixtures generated by tools/ref/gen_app_fixtures.py. */
export class MockClient implements NovationClient {
  async asOf(): Promise<number> {
    return FIXTURE_AS_OF;
  }

  async underlyings(): Promise<Underlying[]> {
    return clone(underlyingsJson as unknown as Underlying[]);
  }

  async chain(underlying: string, expiry?: number) {
    const c = chains[underlying];
    if (!c) throw new Error(`unknown underlying ${underlying}`);
    return clone({ expiries: c.expiries, series: expiry === undefined ? c.series : c.series.filter((s) => s.expiry === expiry) });
  }

  async account(id: number): Promise<AccountData> {
    if (id === marketMaker.id) {
      const { id: mid, owner, state, positions, collateral } = marketMaker;
      return clone({ id: mid, owner, state, positions, collateral });
    }
    if (id !== account7.account.id) throw new Error(`unknown account ${id}`);
    return clone(account7.account);
  }

  /** Fixtures carry REGULAR, EXTENDED and WEEKEND grids for account 7; other sessions (HOLIDAY, HALTED) fall back to REGULAR and report `session: 'REGULAR'`. */
  async scenarioGrid(id: number, session: Session = 'REGULAR'): Promise<ScenarioGrid> {
    if (id === marketMaker.id) return { session: 'REGULAR', cells: clone(marketMaker.grid), shockRange: {} };
    if (id !== account7.account.id) throw new Error(`unknown account ${id}`);
    const exact = account7.grids[session];
    const g = exact ?? account7.grids['REGULAR'];
    if (!g) throw new Error('missing grid');
    return clone({ session: exact ? session : 'REGULAR', cells: g.cells, shockRange: g.shockRange });
  }

  /**
   * Exact when the fixtures carry the ticket: same account, series, size and venue, and a premium
   * within PREMIUM_TOLERANCE of the one the kernel reference priced. Margin, after-trade grid and
   * refusal then come straight from tools/ref/gen_app_fixtures.py. The canned ticket is hedge-bot's;
   * its agent refusal applies only when that agent signs.
   *
   * Any other ticket is an estimate (`approx: true`): the float twin of the kernel (`lib/kernel.ts`)
   * prices the book before and after, and the change is applied to the exact fixture state and grid.
   * Checks run in TradeLogic.trade order: allowed underlying, cash, margin (a pure reduction may stay
   * under IM), then the agent's policy: post-trade lossIM within maxWorstLoss unless the side reduces
   * risk, premium within maxPremiumPerTrade, and equity given up against the mark (fee aside) within
   * the same cap.
   */
  async whatIf(id: number, seriesId: number, qtyDelta: number, premium: number, opts: WhatIfOptions = {}): Promise<Quote> {
    const series = seriesById.get(seriesId);
    if (!series) throw new Error(`unknown series ${seriesId}`);
    if (!Number.isFinite(qtyDelta) || qtyDelta === 0) throw new RangeError('qtyDelta must be a non-zero number');
    const { agent, venue } = opts;
    const acct = await this.account(id);
    const grant = agent
      ? (await this.agents(id)).find((g) => g.agent.toLowerCase() === agent.toLowerCase())
      : undefined;
    if (agent && !grant) throw new Error(`${agent} holds no grant on account ${id}`);

    const tickets = whatifsJson as unknown as CannedTicket[];
    const hit = tickets.find(
      (w) =>
        w.id === id &&
        w.seriesId === seriesId &&
        w.qtyDelta === qtyDelta &&
        (w.venue === undefined || w.venue === venue) &&
        Math.abs(w.premium - premium) <= PREMIUM_TOLERANCE,
    );
    if (hit) {
      const quote = clone(hit.quote);
      const signedByIts = Boolean(agent && hit.agent && agent.toLowerCase() === hit.agent.toLowerCase());
      if (quote.refusal?.code.startsWith('Agent') && !signedByIts) delete quote.refusal;
      return { ...quote, approx: false };
    }

    const s = acct.state;
    const held = acct.positions.find((p) => p.seriesId === seriesId)?.qty ?? 0;
    const next = held + qtyDelta;
    const opening = next !== 0 && (Math.abs(next) > Math.abs(held) || held > 0 !== next > 0);

    const us = await this.underlyings();
    const before = buildBook(acct.positions, acct.collateral, us);
    const after = withTrade(before, series, qtyDelta, us);
    const params = defaultParams(FIXTURE_AS_OF);
    const kb = kernelMargin(params, before.us, before.ps);
    const ka = kernelMargin(params, after.us, after.ps);
    const grid = (await this.scenarioGrid(id)).cells;
    const afterGrid = grid.map((c, i) => c + (ka.grid[i] as number) - (kb.grid[i] as number));

    // premium is a positive magnitude; qtyDelta sign gives direction (buy pays, sell receives).
    const sign = qtyDelta < 0 ? 1 : -1;
    const fee = premium * (FEE_BPS / 1e4);
    const cash = s.cash + sign * premium - fee;
    const mtm = s.mtm + (ka.mtm - kb.mtm);
    const im = s.im + (ka.lossIM - kb.lossIM);
    const equity = s.equity + (cash - s.cash) + (mtm - s.mtm);
    const afterState: AccountState = {
      ...s,
      cash,
      mtm,
      equity,
      im,
      mm: im * MM_RATIO,
      worstScenario: ka.worstScenario,
      deficit: Math.max(0, im - equity),
      healthy: equity >= im,
      liquidatable: equity < im * MM_RATIO,
    };

    const pureReduction = !opening && im <= s.im && equity + fee >= s.equity;
    let refusal: Refusal | undefined;
    if (grant && !grant.allowed.includes(series.underlying))
      refusal = { code: 'AgentUnderlyingNotAllowed', message: `The agent may not trade ${series.underlying}.` };
    else if (cash < 0)
      refusal = { code: 'InsufficientCash', message: 'Cash does not cover the premium and fee.', numbers: { cash, premium, fee } };
    else if (!afterState.healthy && !pureReduction)
      refusal = { code: 'InsufficientMargin', message: 'Initial margin after the trade exceeds equity.', numbers: { im, equity } };
    else if (grant) {
      const loss = s.equity - (equity + fee);
      if (im > grant.maxWorstLoss && (opening || im > s.im)) {
        refusal = {
          code: 'AgentRiskBudgetExceeded',
          message: "Worst-case loss after this trade exceeds the agent's risk budget.",
          numbers: { worstLoss: im, budget: grant.maxWorstLoss, used: s.im, remaining: grant.maxWorstLoss - s.im },
        };
      } else if (premium > grant.maxPremiumPerTrade) {
        refusal = {
          code: 'AgentPremiumExceeded',
          message: "Premium exceeds the agent's per-trade cap.",
          numbers: { premium, cap: grant.maxPremiumPerTrade },
        };
      } else if (loss > grant.maxPremiumPerTrade) {
        refusal = {
          code: 'AgentValueDrainExceeded',
          message: "The trade gives up more value than the agent's cap.",
          numbers: { loss, cap: grant.maxPremiumPerTrade },
        };
      }
    }
    return { premium, fee, after: afterState, ...(refusal ? { refusal } : {}), afterGrid, approx: true };
  }

  async vaults(): Promise<Vault[]> {
    return clone(vaultsJson as unknown as Vault[]);
  }

  async agents(id: number): Promise<AgentGrant[]> {
    return clone((agentsJson as unknown as Record<string, AgentGrant[]>)[String(id)] ?? []);
  }

  async protocol(): Promise<ProtocolStats> {
    return clone(protocolJson);
  }

  async gasTable(): Promise<GasRow[]> {
    return clone(gasJson.rows);
  }

  async refusalsFeed() {
    return clone(refusalsJson as unknown as Awaited<ReturnType<NovationClient['refusalsFeed']>>);
  }
}
