import type {
  AccountState, AgentGrant, GasRow, NovationClient, ProtocolStats, Quote, Refusal, ScenarioGrid, Series, Session, Underlying, Vault,
} from './types';
import underlyingsJson from '../../fixtures/underlyings.json';
import chainsJson from '../../fixtures/chains.json';
import account7Json from '../../fixtures/account7.json';
import whatifsJson from '../../fixtures/whatifs.json';
import marketMakerJson from '../../fixtures/market-maker.json';
import vaultsJson from '../../fixtures/vaults.json';
import agentsJson from '../../fixtures/agents.json';
import protocolJson from '../../fixtures/protocol.json';
import refusalsJson from '../../fixtures/refusals.json';
import gasJson from '../../fixtures/gas.json';

type ChainSeries = Series & { bid: number; ask: number; delta: number; iv: number };
type AccountData = Awaited<ReturnType<NovationClient['account']>>;
type QuoteOut = Quote & { approx?: boolean };

const FEE_BPS = 5;
const MM_RATIO = 0.75;
const account7 = account7Json as unknown as {
  account: AccountData;
  grids: Record<string, { cells: number[]; shockRange: Record<string, number> }>;
};
const chains = chainsJson as unknown as Record<string, { expiries: number[]; series: ChainSeries[] }>;

/** Reads the fixtures generated by tools/ref/gen_app_fixtures.py. */
export class MockClient implements NovationClient {
  async underlyings(): Promise<Underlying[]> {
    return underlyingsJson as unknown as Underlying[];
  }

  async chain(underlying: string, expiry?: number) {
    const c = chains[underlying];
    if (!c) throw new Error(`unknown underlying ${underlying}`);
    return { expiries: c.expiries, series: expiry === undefined ? c.series : c.series.filter((s) => s.expiry === expiry) };
  }

  async account(id: number): Promise<AccountData> {
    if (id !== account7.account.id) throw new Error(`unknown account ${id}`);
    return account7.account;
  }

  async scenarioGrid(id: number, session: Session = 'REGULAR'): Promise<ScenarioGrid> {
    if (id === marketMakerJson.id) return { session: 'REGULAR', cells: marketMakerJson.grid, shockRange: {} };
    if (id !== account7.account.id) throw new Error(`unknown account ${id}`);
    const exact = account7.grids[session];
    const g = exact ?? account7.grids['REGULAR'];
    if (!g) throw new Error('missing grid');
    return { session: exact ? session : 'REGULAR', cells: g.cells, shockRange: g.shockRange };
  }

  /**
   * Exact when the fixtures carry the ticket (computed by the integer kernel reference).
   * Otherwise a float approximation: the premium moves cash and the current margin is
   * scaled by the change in short exposure. Labelled `approx: true`; it is a UI
   * placeholder, never a substitute for the kernel.
   */
  async whatIf(id: number, seriesId: number, qtyDelta: number, premium: number): Promise<QuoteOut> {
    const tickets = whatifsJson as unknown as { id: number; seriesId: number; qtyDelta: number; premium: number; quote: Quote }[];
    const hit = tickets.find((w) => w.id === id && w.seriesId === seriesId && w.qtyDelta === qtyDelta);
    if (hit) return { ...hit.quote, approx: false };
    const acct = await this.account(id);
    const s = acct.state;
    const held = acct.positions.find((p) => p.seriesId === seriesId);
    const shortBefore = held && held.qty < 0 ? -held.qty : 0;
    const shortAfter = Math.max(0, -((held?.qty ?? 0) + qtyDelta));
    const scale = shortBefore > 0 ? shortAfter / shortBefore : 1 + Math.max(0, -qtyDelta) / 100;
    const fee = Math.abs(premium) * (FEE_BPS / 1e4);
    const cash = s.cash - premium - fee;
    const im = s.im * scale;
    const equity = cash + s.mtm + premium;
    const after: AccountState = {
      ...s, cash, equity, im, mm: im * MM_RATIO, deficit: Math.max(0, im - equity), healthy: equity >= im, liquidatable: equity < im * MM_RATIO,
    };
    let refusal: Refusal | undefined;
    if (cash < 0) refusal = { code: 'InsufficientCash', message: 'Cash does not cover the premium and fee.', numbers: { cash, premium, fee } };
    else if (!after.healthy) refusal = { code: 'InsufficientMargin', message: 'Initial margin after the trade exceeds equity.', numbers: { im: after.im, equity: after.equity } };
    return { premium, fee, after, ...(refusal ? { refusal } : {}), approx: true };
  }

  async vaults(): Promise<Vault[]> {
    return vaultsJson as unknown as Vault[];
  }

  async agents(id: number): Promise<AgentGrant[]> {
    return (agentsJson as unknown as Record<string, AgentGrant[]>)[String(id)] ?? [];
  }

  async protocol(): Promise<ProtocolStats> {
    return protocolJson;
  }

  async gasTable(): Promise<GasRow[]> {
    return gasJson.rows;
  }

  async refusalsFeed() {
    return refusalsJson as unknown as Awaited<ReturnType<NovationClient['refusalsFeed']>>;
  }
}
