import type {
  AccountState, AgentGrant, GasRow, NovationClient, ProtocolStats, Quote, Refusal, ScenarioGrid, Series, Session, Underlying, Vault,
} from './types';
import underlyingsJson from '../../fixtures/underlyings.json';
import chainsJson from '../../fixtures/chains.json';
import account7Json from '../../fixtures/account7.json';
import whatifsJson from '../../fixtures/whatifs.json';
import marketMakerJson from '../../fixtures/market-maker.json';
import vaultsJson from '../../fixtures/vaults.json';
import agentsJson from '../../fixtures/agents.json';
import protocolJson from '../../fixtures/protocol.json';
import refusalsJson from '../../fixtures/refusals.json';
import gasJson from '../../fixtures/gas.json';
import { buildBook, defaultParams, kernelMargin, RISK, withTrade } from '../kernel';

type ChainSeries = Series & { bid: number; ask: number; delta: number; iv: number };
type AccountData = Awaited<ReturnType<NovationClient['account']>>;

/** tools/ref/gen_app_fixtures.py NOW: every fixture mark, grid and margin is priced at this second. */
export const FIXTURE_AS_OF = 1790697600;
const FEE_BPS = 5;
const MM_RATIO = RISK.mmRatio;
const account7 = account7Json as unknown as {
  account: AccountData;
  grids: Record<string, { cells: number[]; shockRange: Record<string, number> }>;
};
const marketMaker = marketMakerJson as unknown as AccountData & { grid: number[] };
const clone = <T,>(v: T): T => structuredClone(v);
const chains = chainsJson as unknown as Record<string, { expiries: number[]; series: ChainSeries[] }>;
const seriesById = new Map<number, ChainSeries>(Object.values(chains).flatMap((c) => c.series.map((s) => [s.id, s] as const)));

/** Reads the fixtures generated by tools/ref/gen_app_fixtures.py. */
export class MockClient implements NovationClient {
  async asOf(): Promise<number> {
    return FIXTURE_AS_OF;
  }

  async underlyings(): Promise<Underlying[]> {
    return clone(underlyingsJson as unknown as Underlying[]);
  }

  async chain(underlying: string, expiry?: number) {
    const c = chains[underlying];
    if (!c) throw new Error(`unknown underlying ${underlying}`);
    return clone({ expiries: c.expiries, series: expiry === undefined ? c.series : c.series.filter((s) => s.expiry === expiry) });
  }

  async account(id: number): Promise<AccountData> {
    if (id === marketMaker.id) {
      const { id: mid, owner, state, positions, collateral } = marketMaker;
      return clone({ id: mid, owner, state, positions, collateral });
    }
    if (id !== account7.account.id) throw new Error(`unknown account ${id}`);
    return clone(account7.account);
  }

  /** Fixtures carry REGULAR, EXTENDED and WEEKEND grids for account 7; other sessions (HOLIDAY, HALTED) fall back to REGULAR and report `session: 'REGULAR'`. */
  async scenarioGrid(id: number, session: Session = 'REGULAR'): Promise<ScenarioGrid> {
    if (id === marketMaker.id) return { session: 'REGULAR', cells: clone(marketMaker.grid), shockRange: {} };
    if (id !== account7.account.id) throw new Error(`unknown account ${id}`);
    const exact = account7.grids[session];
    const g = exact ?? account7.grids['REGULAR'];
    if (!g) throw new Error('missing grid');
    return clone({ session: exact ? session : 'REGULAR', cells: g.cells, shockRange: g.shockRange });
  }

  /**
   * Exact when the fixtures carry the ticket (computed by the integer kernel reference). Otherwise
   * the float twin of the kernel (`lib/kernel.ts`) prices the book before and after, and the change
   * is applied to the exact fixture state; such quotes are labelled `approx: true`. The after-trade
   * grid is the exact fixture grid plus the twin's change, on both paths.
   *
   * The canned ticket is hedge-bot's: its budget refusal applies only when `agent` signs. For other
   * tickets an agent is held to the generator's budget rule: used + growth of the correlated loss
   * must stay within `maxWorstLoss`. The allowed-underlyings list is left to the caller.
   */
  async whatIf(id: number, seriesId: number, qtyDelta: number, premium: number, agent?: string): Promise<Quote> {
    const series = seriesById.get(seriesId);
    if (!series) throw new Error(`unknown series ${seriesId}`);
    if (!Number.isFinite(qtyDelta) || qtyDelta === 0) throw new RangeError('qtyDelta must be a non-zero number');
    const acct = await this.account(id);
    const grant = agent
      ? (await this.agents(id)).find((g) => g.agent.toLowerCase() === agent.toLowerCase())
      : undefined;
    if (agent && !grant) throw new Error(`${agent} holds no grant on account ${id}`);

    const us = await this.underlyings();
    const before = buildBook(acct.positions, acct.collateral, us);
    const after = withTrade(before, series, qtyDelta, us);
    const params = defaultParams(FIXTURE_AS_OF);
    const kb = kernelMargin(params, before.us, before.ps);
    const ka = kernelMargin(params, after.us, after.ps);
    const grid = (await this.scenarioGrid(id)).cells;
    const afterGrid = grid.map((c, i) => c + (ka.grid[i] as number) - (kb.grid[i] as number));

    const tickets = whatifsJson as unknown as { id: number; seriesId: number; qtyDelta: number; premium: number; quote: Quote }[];
    const hit = tickets.find((w) => w.id === id && w.seriesId === seriesId && w.qtyDelta === qtyDelta);
    if (hit) {
      const quote = clone(hit.quote);
      if (!grant && quote.refusal?.code === 'AgentRiskBudgetExceeded') delete quote.refusal;
      return { ...quote, afterGrid, approx: false };
    }

    const s = acct.state;
    // premium is a positive magnitude; qtyDelta sign gives direction (buy pays, sell receives).
    const sign = qtyDelta < 0 ? 1 : -1;
    const fee = premium * (FEE_BPS / 1e4);
    const cash = s.cash + sign * premium - fee;
    const mtm = s.mtm + (ka.mtm - kb.mtm);
    const im = s.im + (ka.lossIM - kb.lossIM);
    const equity = s.equity + (cash - s.cash) + (mtm - s.mtm);
    const afterState: AccountState = {
      ...s,
      cash,
      mtm,
      equity,
      im,
      mm: im * MM_RATIO,
      worstScenario: ka.worstScenario,
      deficit: Math.max(0, im - equity),
      healthy: equity >= im,
      liquidatable: equity < im * MM_RATIO,
    };
    // Spec 5.3: a trade that lowers lossIM and grows no series clears even below initial margin.
    const held = acct.positions.find((p) => p.seriesId === seriesId)?.qty ?? 0;
    const reducing = ka.lossIM <= kb.lossIM && Math.abs(held + qtyDelta) <= Math.abs(held);
    let refusal: Refusal | undefined;
    if (cash < 0) refusal = { code: 'InsufficientCash', message: 'Cash does not cover the premium and fee.', numbers: { cash, premium, fee } };
    else if (!afterState.healthy && !reducing)
      refusal = { code: 'InsufficientMargin', message: 'Initial margin after the trade exceeds equity.', numbers: { im, equity } };
    else if (grant) {
      const projected = grant.used + Math.max(0, ka.lossCorr - kb.lossCorr);
      if (projected > grant.maxWorstLoss) {
        refusal = {
          code: 'AgentRiskBudgetExceeded',
          message: "Worst-case loss after this trade exceeds the agent's risk budget.",
          numbers: {
            worstLoss: Math.round(projected * 100) / 100,
            budget: grant.maxWorstLoss,
            used: grant.used,
            remaining: grant.maxWorstLoss - grant.used,
          },
        };
      }
    }
    return { premium, fee, after: afterState, ...(refusal ? { refusal } : {}), afterGrid, approx: true };
  }

  async vaults(): Promise<Vault[]> {
    return clone(vaultsJson as unknown as Vault[]);
  }

  async agents(id: number): Promise<AgentGrant[]> {
    return clone((agentsJson as unknown as Record<string, AgentGrant[]>)[String(id)] ?? []);
  }

  async protocol(): Promise<ProtocolStats> {
    return clone(protocolJson);
  }

  async gasTable(): Promise<GasRow[]> {
    return clone(gasJson.rows);
  }

  async refusalsFeed() {
    return clone(refusalsJson as unknown as Awaited<ReturnType<NovationClient['refusalsFeed']>>);
  }
}
